### ISSUE TITLE
Issue with lib1 postbuild for GasProject2 

### ISSUE THREAD

**Issue by shaycapehart** [PopGoesTheWza/ts-gas-project-starter#4]
There seems to be an issue during the postbuild for GasProject2.  The script in package.json is as follows: 

`"postbuild-project2": "copyfiles -u 2 build/common-components/lib1.js build/gas/GasProject2"`

Nothing is actually copied because there is no lib1.js file in the common-components library. Is that supposed to be copying the entire lib1 folder, just lib1/index.js, or should tsconfig.json be configured to generate a lib1.js file?

Thanks,
Shay

**Comment by PopGoesTheWza** [comment]
@shaycapehart thanks for pointing it out. It should now be fixed.
